//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAUploadForWinform
{
    using System;
    using System.Collections.Generic;
    
    public partial class kkinfo
    {
        public string kkCode { get; set; }
        public string kkName { get; set; }
        public Nullable<System.DateTime> startTime1 { get; set; }
        public Nullable<System.DateTime> endTime1 { get; set; }
        public Nullable<System.DateTime> startTime2 { get; set; }
        public Nullable<System.DateTime> endTime2 { get; set; }
        public Nullable<System.DateTime> startTime3 { get; set; }
        public Nullable<System.DateTime> endTime3 { get; set; }
        public System.DateTime createTime { get; set; }
        public string creator { get; set; }
        public string dptCode { get; set; }
        public string dptName { get; set; }
        public string orgCode { get; set; }
        public string orgName { get; set; }
        public Nullable<System.DateTime> tempDayStart { get; set; }
        public Nullable<System.DateTime> tempDayEnd { get; set; }
        public Nullable<System.DateTime> tempStartTime1 { get; set; }
        public Nullable<System.DateTime> tempEndTime1 { get; set; }
        public Nullable<System.DateTime> tempStartTime2 { get; set; }
        public Nullable<System.DateTime> tempEndTime2 { get; set; }
        public Nullable<System.DateTime> tempStartTime3 { get; set; }
        public Nullable<System.DateTime> tempEndTime3 { get; set; }
    }
}
