//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAUploadForWinform
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploadfail
    {
        public long id { get; set; }
        public string kkcode { get; set; }
        public string kkName { get; set; }
        public System.DateTime passTime { get; set; }
        public string hphm { get; set; }
        public string hpys { get; set; }
        public string wfdd { get; set; }
        public string wflx { get; set; }
        public string cjjg { get; set; }
    }
}
